version: "3"
services:
    web:
        build: .
        command: python main.python
        links:
            - db
    db:
        image: postgres
        container_name: "postgres_queens"
        environment: 
            - POSTGRES_USER=brime
            - POSTGRES_PASSWORD=panda
            - POSTGRES_DB=queensdb
        ports:
            - "54320:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data